.github/main.workflow

Follow up https://github.com/cats-oss/github-action-detect-unmergeable/pull/12

Specify self via local path

---

.github/main.workflow

Reverts cats-oss/github-action-detect-unmergeable#13

Revert "Specify self via local path"

---

LICENSE.MIT

Fix https://github.com/cats-oss/github-action-detect-unmergeable/issues/2

Add LICENSE.MIT 

---

.github/main.workflow
src/index.js
src/operations.js

ref https://github.com/cats-oss/github-action-detect-unmergeable/pull/18

Remove ENABLE_CHECK_RELATIONSHIP_BETWEEN_PUSHED_AND_PR flag

---

Makefile

Follow up https://github.com/cats-oss/github-action-detect-unmergeable/pull/26

Rewrite Makefile for Go Implementation

---

Makefile

Retry https://github.com/cats-oss/github-action-detect-unmergeable/pull/31

[Retry #31]  Rewrite Makefile for Go Implementation 

---

.circleci/config.yml

https://github.com/cats-oss/github-action-detect-unmergeable/issues/4

Update CiecleCI configuration

---

go.mod
go.sum

with 'go version go1.12.5 darwin/amd64'
This is for clean up.

Recreate go.mod by 'GO111MODULE=on go mod tidy'

---

.github/main.workflow
.github/workflows/push.yml

Fix https://github.com/cats-oss/github-action-detect-unmergeable/issues/59

Migrate workflow to new syntax

---

action.yml

Based on https://github.com/actions/container-template/blob/master/action.yml

Add action.yml as new GitHub Action metadata

---

README.md

Fix https://github.com/cats-oss/github-action-detect-unmergeable/issues/66

Add the example for new YAML config 

---

.github/workflows/detect_unmergeable_pull_request.yml

* Follow up https://github.com/cats-oss/github-action-detect-unmergeable/pull/74
* I forgot `""`

Don't run "Detect unmergeable PRs" on pushing any tags (retry 74)

---

go.mod
go.sum
main.go
operation.go

https://github.com/google/go-github/releases

Upgrade go-github to v28

---

.circleci/config.yml
Dockerfile

golang v1.13 docker image does not support 'stretch'

Use the docker image based on buster

---

.circleci/config.yml
Dockerfile
go.mod
go.sum

Upgrade to Go v1.13

---

.github/workflows/detect_unmergeable_pull_request.yml

This attempt to fix the stopped workflow

Allow on pushing to all branches

---

Dockerfile
README.md

Fix https://github.com/cats-oss/github-action-detect-unmergeable/issues/70

Remove LABEL for legacy GitHub Actions

---

.github/workflows/detect_unmergeable_pull_request.yml
README.md
json.go
main.go
operation.go

https://github.com/cats-oss/github-action-detect-unmergeable/issues/29

Remove the label if Pull Request's mergeable state recover from false

---

main.go

https://github.com/cats-oss/github-action-detect-unmergeable/issues/29

Add the log about working mode

---

json.go
main.go
operation.go

https://github.com/cats-oss/github-action-detect-unmergeable/issues/29

Workaround to fail to parse json in pull request sync path

---

main.go

https://github.com/cats-oss/github-action-detect-unmergeable/issues/29

Add the log if this action sucess to remove the label 

---

.github/workflows/ci.yml
go.mod

related https://github.com/cats-oss/github-action-detect-unmergeable/pull/109

Upgrade go to 1.15

---

go.sum

This follow up https://github.com/cats-oss/github-action-detect-unmergeable/pull/108

Regenerate go.sum to cleanup

---

go.mod
go.sum
main.go
operation.go

https://github.com/google/go-github/releases

Update go-github to v35
